sudo: false
language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=flake8
      install: pip install tox
      script: tox -e $TOX_ENV

install:
    - pip install tox-travis codecov

script:
    - tox

after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#exhibition"
        use_notice: true
